### ISSUE TITLE
Abandoned?!

### ISSUE THREAD

**Issue by JaredBanyard** [facebook/conceal#100]
Seriously Facebook.  You put out a project like this and then abandon it?  Don't tell us you haven't because it hasn't been updated in ages.  Don't let a great library die, please put a little effort into fixing this for 64-bit, Marshmallow, and maintaining a proper Maven version.  Lets start hitting their twitter and other accounts to get them to respond.

**Comment by shaver** [comment]
Hey @JaredBanyard. I work at Facebook, and I think you're right: we haven't done a good job of maintaining Conceal or working with its community of users. I'm in the process of building a team to take over Conceal and get it back in shape both technically and as a project, and I'll post -- somewhere? -- when we get a more concrete plan in place.

Sorry you haven't had a good experience with Conceal lately; my hope is that we'll be able to make it a library you love using again in the near future.

**Comment by siyengar** [comment]
Hey @JaredBanyard sorry about making you wait for long. I've put up a fix for the issues you mentioned in https://github.com/facebook/conceal/pull/101, at least the 64 bit problem based on @aalaniz's pull request. It should be in a day or 2. I think this should also fix the marshmallow problem as well.

**Comment by JaredBanyard** [comment]
@siyengar Thanks, cant wait for a new maven release

**Comment by siyengar** [comment]
Closing out since the issues are being worked on
