### ISSUE TITLE
Conflicts using in React Native project

### ISSUE THREAD

**Issue by corymsmith** [facebook/conceal#102]
I'm working on some updates to https://github.com/oblador/react-native-keychain that adds support for Conceal. When I include my project in the gradle file I get the following error: 

com.android.dex.DexException: Multiple dex files define Lcom/facebook/proguard/annotations/DoNotStrip

It looks like its because both React Native and Conceal use the same fully qualified package name, any ideas on how to sort this out? Maybe rename the package name in this project?

https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/proguard/annotations/DoNotStrip.java

https://github.com/facebook/conceal/blob/master/java/com/facebook/proguard/annotations/DoNotStrip.java

**Comment by siyengar** [comment]
Thanks for reporting, I'd be happy to accept a change to move the package of DonotStrip in conceal. Do you want to send a pull request?

**Comment by corymsmith** [comment]
Definitely. I'll move it to com.facebook.crypto.annotations to match the other libs. Should we also move the other annotations as well?

**Comment by corymsmith** [comment]
Correction, will move to com.facebook.crypto.proguard.annotations. Just got buck all setup up and tests passing so good to go

**Comment by corymsmith** [comment]
@siyengar Any idea when you'll be publishing an updated version to Maven Central?

**Comment by siyengar** [comment]
i just published 1.0.3 to mvn central which should have this change

**Comment by corymsmith** [comment]
Thanks so much, really appreciate the work you and your team are doing on this and many other open source projects.

**Comment by corymsmith** [comment]
@siyengar what else is included in that maven release?

**Comment by siyengar** [comment]
1.0.3 also contains 64 bit binaries for conceal so that it can work on 64 bit platforms https://github.com/facebook/conceal/issues/67

**Comment by corymsmith** [comment]
Perfect, that was my hope. Thanks again!
