### ISSUE TITLE
Unit tests won't run

### ISSUE THREAD

**Issue by corymsmith** [facebook/conceal#104]
I can run the integration tests but when I run:

`buck test javatests/com/facebook/crypto:crypto`

I get the following error:

No build file at javatests/com/facebook/crypto/BUCK when resolving target //javatests/com/facebook/crypto:crypto.

**Comment by corymsmith** [comment]
I'm not super familiar with buck but it seems like `buck test` works, should I update the readme to reflect that?

**Comment by corymsmith** [comment]
@siyengar I can add that to the Readme if it makes sense and just include it in my other PR if you want?

**Comment by siyengar** [comment]
Ya that should be updated as well, great catch. Would appreciate it

**Comment by corymsmith** [comment]
Ok. Will take care of that today / tomorrow
