### ISSUE TITLE
Hardcoded IV in CipherHelper Class

### ISSUE THREAD

**Issue by oba2cat3** [facebook/conceal#114]
the CipherHelper Class has a hard coded IV length - that is a problem if you implement a KeyChain class of your own, and change the IV length there. 
Consider the following fixes :
1. support arbitrary length IV - not recommended.
2. make the IV method override optional (change KeyChain to be an Abstract Class), and JavaDoc it.

Problem hardcoded value from the CipherHelper class:
`public InputStream getCipherInputStream(InputStream cipherStream, Entity entity, byte cryptoVersion, byte cipherID) throws IOException, KeyChainException, CryptoInitializationException {
       ....
        byte[] iv = new byte[12];
        ...
    }`

**Comment by helios175** [comment]
Solved with #123

**Comment by helios175** [comment]
Now the library offers support for 128 and 256 bit keys.
IV length is intended to be 12 bytes as recommended for both cases.
It could be extended in the future in new `CryptoConfig`s but only if there's a new encryption config that offers something extra (like having a 512 bit key).
