### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by JaredBanyard** [facebook/conceal#115]
So, I'm trying 1.0.3 for 64-bit support and getting errors like this:
`Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NoSuchFieldError: no "J" field "mCtxPtr" in class "Lcom/facebook/crypto/cipher/NativeGCMCipher;" or its superclasses'`

**Comment by helios175** [comment]
This is probably related to proguard optimization.
When proguard minimizes the names of Java classes it shouldn't do for those members accessed from native code, as mCtxPtr. So you need to tell proguard what not to obfuscate.

There is a `proguard_annotations.pro` file in the root folder. You can use it as is to configure proguard (for release builds probably, as debug builds don't usually run proguard).

If you have more rules to be applied, you can merge the content of the file with yours.
