### ISSUE TITLE
v1.0.4 is not on Maven Central

### ISSUE THREAD

**Issue by Schnouki** [facebook/conceal#118]
Hi,

It seems that v1.0.4 is not available on Maven Central yet. Could you please publish it there?

Thanks a lot!

**Comment by cotfas** [comment]
Looking forward for 1.04 on maven..

**Comment by helios175** [comment]
We are about to upload it. Now we are merging some configuration fix we needed to upload this version.
I'll close this ticket once available.

**Comment by helios175** [comment]
It's available now.
Sorry about the delay!
