### ISSUE TITLE
Compiled native source code of Conceal

### ISSUE THREAD

**Issue by cotfas** [facebook/conceal#119]
Hello guys,

Is there anyone can compile for me the conceal native source code for all processors?

I`ve looked into:

https://raw.github.com/facebook/conceal/gh-pages/downloads/libs.zip

But it is only compiled for armeabi, armeabi-v7a, x86

And, I need also to have for x86_64, arm64-v8a and mips

It is mandatory to have for x86_64, and arm64-v8a.. (mips is not important but if it is available, thats good)

(I`ve tried to compile by myself but I do not have Linux and Buck, and I`ve got a lot of issues with Windows and Android Studio, even tought I have NDK installed)....

Thank you in advance.

**Comment by helios175** [comment]
We are not supporting the downloads directory anymore.

You can get the compiled libraries from the Maven repository.
Download the `.aar` file from [the Maven Central repository](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.facebook.conceal%22%20AND%20a%3A%22conceal%22)
Version `1.0.4` is being published, it takes some time to appear.
Then you can unzip the `.aar` file and get the libraries you need from the `/jni` folder.

**Comment by cotfas** [comment]
Thanks

:)
