### ISSUE TITLE
Add libraries in other languages as well for interop

### ISSUE THREAD

**Issue by siyengar** [facebook/conceal#12]
Add libraries for Conceal in other languages so that servers can decrypt data clients send them. It should also be version aware.

**Comment by ahmadazimi** [comment]
This is important for developers to decrypt encrypted data via ```Conceal``` in a server side application, for example, a ```PHP application```.

I've searched everywhere to find any documentation about decrypting ```Conceal``` output in ```PHP```, but unfortunately I couldn't find anything!

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by nimesh217** [comment]
Please inform is there any update for conceal support for php?

**Comment by shaver** [comment]
We don't have active plans for PHP language bindings, but would welcome contributions of them.

**Comment by nimesh217** [comment]
@shaver I am ready to go for the development of facebook conceal in PHP, will you guide me for this?

**Comment by helios175** [comment]
Closing this issue for now.
Conceal 2.0 is ported to C++ so it should be easier to build wrappers for different languages thou.
