### ISSUE TITLE
API Request :  encrypt(String plaintText) //return encrypted text

### ISSUE THREAD

**Issue by MufriA** [facebook/conceal#13]
As of now, encrypted text are written / read from file, is it possible to add API to get the encrypted text for plain text and use any other way to store, say in database or shared preference.

```
public String encrypt(String plaintText) //return encrypted text
public String decrtpt(String encryptedText) // return decrypted text
```

**Comment by huttarl** [comment]
The link above for SharedPrefsBackedKeyChain.java is broken, but the newer URL is https://github.com/facebook/conceal/blob/master/java/com/facebook/android/crypto/keychain/SharedPrefsBackedKeyChain.java (insert /android before /crypto).
