### ISSUE TITLE
Can devices share the same encrypted file?

### ISSUE THREAD

**Issue by speedpursuer** [facebook/conceal#151]
In my use case, I wanted one encrypted file can be decrypted by any device if it has the key/password.

I think it would be similar to [this](https://github.com/facebook/conceal/issues/19) and [this](https://github.com/facebook/conceal/issues/49) and should be achieved by a customized KeyChain implementation. 

I'm just wondering if it will be helpful to provide a sample implementation to use a single string key if this is a common use case. So users like me who may not be familiar with KeyChain can use the lib out of box in their such simpler scenario. 

Thanks!

**Comment by helios175** [comment]
Just starting to answer old issues.

Encryption is deterministic if KEY,IV and Entity are the same.
IV is generated randomly when encrypting, but it's included in the encrypted result.

So yes, another device will be able to read encrypted content if they have the same Key, and use the same Entity (Entity is used at the end, to run a hash check to avoid tampering). Entity is not expected to be a secret. Key, obviously is.

So as long as you have the same key you'll be fine.
To use the same key: either change the SharedPrefsKeyChain object to allow saving it, or just implement KeyChain returning the key you want to use.

Remember that the key should be sent in a secure way and that's very very important :)

Feel free to reopen. Now I'll be around to answer.
