### ISSUE TITLE
[question] Can I get latest binaries or binaries for v1.1 ?

### ISSUE THREAD

**Issue by prateek-kaushik** [facebook/conceal#153]
The binaries currently available to download doesn't seem to be updated ones as I could not find the new additions like CryptoConfig class and Entity class updates. 
Correct me if I'm missing something.
Thanks.

**Comment by helios175** [comment]
You should have v1.1.2 available on maven.
You can also download it manually from
http://central.maven.org/maven2/com/facebook/conceal/conceal/1.1.2/
