### ISSUE TITLE
multiple threads 

### ISSUE THREAD

**Issue by zhuxiaogit** [facebook/conceal#154]
Can Conceal use multiple threads encry my big data?

**Comment by helios175** [comment]
Sorry about leaving this thread unanswered.

In principle Conceal encryption/decryption is not thread safe. It needs to process in a single thread whatever you encrypt/decrypt. That also has to do with the requirements of the encryption algorithm. Nevertheless nothing prevents you from using several threads each of them encrypting/decrypting their own, independent part.

There could be some helper to do this, but I'm thinking of:

In fact that could be done on top of current Conceal in a pretty-straight-forward way:

* getFile, check length
* spawn several threads, each one:
  * gets its own input stream for the correct range of the file/content
  * initializes encryption independently, they should use some "entity+id" identification to enforce integrity
  * each of them process al their input and output everything
* if you need to output everything to one file, probably an outputstream that writes to a RandomAccessFile to the right position can be easily provided
* when all threads end the RAF is closed
* bear in mind that as you are encrypting each piece independently each range will produce 30bytes more (so RAF writing should have that into mind): 2 bytes for format, 12 for IV, 16 for integrity tag. Not sure if that info is available but it can be made pretty easily.
