### ISSUE TITLE
Conceal increases android app size substantially

### ISSUE THREAD

**Issue by Winghin2517** [facebook/conceal#155]
I wrote a post on SO on the size of my android app after importing conceal into my app:

http://stackoverflow.com/questions/38730370/facebook-conceal-takes-up-a-lot-of-space-on-an-app

For a 11.7mb app, the Conceal libraries takes up about 2.6mb. That is 22% of my app size.

<img width="947" alt="screen shot 2016-08-02 at 10 57 31 pm" src="https://cloud.githubusercontent.com/assets/7094734/17345233/5efdc1c8-5905-11e6-9193-1b7357a2bf0a.png">

Is there a way to reduce the size of the libraries so that my app size can reduce?

**Comment by Vandalko** [comment]
Have you tried APK splits http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits ?
It would require some additional work with multiple APKs (https://developer.android.com/google/play/publishing/multiple-apks.html) but arm users (which are majority) would not have to download x86 libs

**Comment by helios175** [comment]
I totally subscribe what Vandalko suggest: creating different APKs for each target platform. That prevents unnecessary multiplication of native code.

On the other hand: #161 made the library much much smaller but correctly configuring the compiler and the linker. Conceal native library (libconceal.so) uses OpenSSL native library internally. We only use a small portion of it but not all what could be discarded was discarded.

The new commit changes configuration (Makefile) to make each OpenSSL function able to be discarded, and our compile configuration (Android.mk) to take advantage of it by declaring OpenSSL library private and discarding unused sections.

**Comment by helios175** [comment]
In the next days I will emit a new version of the library so it's available in Maven.

**Comment by helios175** [comment]
Conceal 1.1.3 is ready to download from Maven. The library file for x86_64 goes from 1.5MB to 260kb uncompressed. So it will really make a difference.

Thanks a lot for alerting on this!

**Comment by Winghin2517** [comment]
Thanks - I tried your latest library with my app by building it with conceal 1.1.3 (i did not use apk split) and uploaded it to nimbleandroid to test:

<img width="967" alt="screen shot 2016-09-21 at 10 37 11 am" src="https://cloud.githubusercontent.com/assets/7094734/18703920/369b7220-7fe8-11e6-89d2-d992ec4f24b8.png">

The size of the Conceal library so files went from 2.6mb to 200kb - a tenth of the size.

My only concern now is the arm libraries do not appear anymore, unlike my initial screenshot which shows that my app contained both the x86 and arm libraries. Is there a reason why the arm libraries are no longer included?

**Comment by helios175** [comment]
I checked the sample app I used to test the conceal 1.1.3 and it includes the files. I didn't change any of the configuration producing for different architectures, so it should be there.

I would check if your report includes files over 100KB only, because the title says "Large Files". If so the arm files are smaller than x86 as you can see in my listing below.

I would unzip your app's apk and check if files are there.

```
$ unzip -l app/build/outputs/apk/app-debug.apk | grep conceal
   267928  09-20-16 11:56   lib/arm64-v8a/libconceal.so
   198028  09-20-16 11:56   lib/armeabi/libconceal.so
   210328  09-20-16 11:56   lib/armeabi-v7a/libconceal.so
   263556  09-20-16 11:56   lib/x86/libconceal.so
   276424  09-20-16 11:56   lib/x86_64/libconceal.so

$ unzip -l app/build/outputs/apk/app-release-unsigned.apk | grep conceal
   267928  09-20-16 11:56   lib/arm64-v8a/libconceal.so
   198028  09-20-16 11:56   lib/armeabi/libconceal.so
   210328  09-20-16 11:56   lib/armeabi-v7a/libconceal.so
   263556  09-20-16 11:56   lib/x86/libconceal.so
   276424  09-20-16 11:56   lib/x86_64/libconceal.so
```
