### ISSUE TITLE
Importing through Maven central does not work

### ISSUE THREAD

**Issue by rohitramkumar308** [facebook/conceal#163]
I have added the following import to my gradle:
com.facebook.conceal:conceal:1.1.3

I still get errors:
Error:(6, 27) error: package com.facebook.crypto does not exist
Error:(5, 44) error: package com.facebook.android.crypto.keychain does not exist

It works only when the conceal.jar and conceal_android.jar are present

**Comment by pinball83** [comment]
You must use such dependency in your build.gradle file: compile 'com.facebook.conceal:conceal:1.1.3@aar'

if you omit

@aar
gradle import it but nothing would work
