### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by shaunkawano** [facebook/conceal#164]
The links written on README and library description seems broken; I am guessing the official website for conceal library has gone or moved to somewhere else.

http://facebook.github.io/conceal/
http://facebook.github.io/conceal/documentation/

**Comment by pinball83** [comment]
You must use such dependency in your build.gradle file: compile 'com.facebook.conceal:conceal:1.1.3**@aar**'

if you omit aar gradle import it but nothing would work

**Comment by shaunkawano** [comment]
@pinball83 I am referring to the library websites, which are the URL link listed above. I am not referring to the gradle dependency or whatsoever.

**Comment by pinball83** [comment]
sorry I missed the thread

**Comment by helios175** [comment]
The pages were restored.
The branch containing the documentation was inadvertently deleted.
Anyway it needs update as API is improved and jars are old.
I created #168 for that matter.
