### ISSUE TITLE
IO Exception : unexpected crypto version -1

### ISSUE THREAD

**Issue by Pingsh** [facebook/conceal#167]
Decryption problems:

Positioning:
CryptoAlgoGcm.class ---public InputStream wrap(InputStream is, Entity entity)
cryptoVersion = -1;
cipherID = -1;

I find on stackoverflow,  but no one proposed solution.

**Comment by helios175** [comment]
Not sure if I understand it correctly. But this seems to say that when configuring decryption, when wrapping the input stream... it fails to recognize a valid prefix.

A valid Conceal encrypted content starts with format_version and cipher_id. Format version is (byte) 0x01 and cipherID can be 0x01 or 0x02 (128 bits key, or 256 bits key). When you call wrap input stream, it reads the header right away (version, id, and IV) so decryption can start.

If it doesn't find valid values... it will throw an exception.

I would check in fact if the stream is not at EOF and method `read()` is returning `-1` all the time.
