### ISSUE TITLE
App crashes when running as 64 bit version: `libfb.so is 64-bit instead of 32-bit`

### ISSUE THREAD

**Issue by astr0-4** [facebook/conceal#206]
I'm testing out my app to ensure it runs on 64 bit architecture. When running the app after installing with adb: `adb install --abi armeabi-v7a app-dev-debug.apk`, the app installs fine, but crashes on login with the error: 
```2019-06-07 14:24:48.900 24946-25067/com.aimsio.app.dev E/com.facebook.soloader.NativeLibrary: Failed to load native lib: 
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.aimsio.app.dev/lib-main/libfb.so" is 64-bit instead of 32-bit
```
I am using conceal, and when I inspect the apk, the 64bit version of the library is present: 
<img width="268" alt="Screen Shot 2019-06-07 at 3 41 41 PM" src="https://user-images.githubusercontent.com/6060764/59137082-d8ce0680-893a-11e9-81f5-5388fb19c129.png">

I'm not sure what the cause of this crash is but it happens when the app tries to load the conceal library. I'm relatively new to android development so I could be doing something wrong but I followed the [guide for ensuring the app will run on 64-bit devices](https://developer.android.com/distribute/best-practices/develop/64-bit) and can't get past this.

**Comment by lbelavoir** [comment]
@astr0-4 any clue about why you had this behaviour ?
