### ISSUE TITLE
Different AES options

### ISSUE THREAD

**Issue by friscoMad** [facebook/conceal#23]
As told here: http://stackoverflow.com/questions/22662332/heap-corruption-segv-maperr-in-android-native-code?noredirect=1#comment34648412_22662332

I am opening a issue to say that some other encoding format sould be supported, in my case AES CBC with different keysizes are a must so I needed to rewrite almost the whole library. 

Aslo as it is now it should be optional to use the keyring as maybe the keys are shared between devices.
Another design decission that I didn't liked is that crypto and nativeLibrary instances must be shared within the app or recreated every time (this tries to load jni libraries every time so it is a lot more time consuming), simple singletons will be a lot more efficient.

Aside for that I found that BetterCipherInputStream does not support any cipher that requires calling doFinal (usually padded ciphers) so a major rewite was needed there (https://github.com/frisco82/conceal/blob/master/java/com/facebook/crypto/streams/BetterCipherInputStream.java), having an option to define the buffer size is a must also, depending on the use cases 256bytes it is too low and the overhead of jni will add up.

In my case I found that openssl cipherUpdate could overflow the output buffer (or maybe it was jni ReleaseByteArrayElements after a number of calls within the same context, I was unable to fully debug it so I added an extra block to the buffer to avoid the memory corruption.

Aside from that there are minor optimizations that I made in my work:
- Key and iv does not need to be stored with the context, it makes it's own copies, so a struct is not needed, just store a pointer to the context.
- NativeFaliure should be cached java-side as those are more jni calls for no reason.
- Init method can be changed to support multiple key sizes easily and using CipherInit the code will be cleaner.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by helios175** [comment]
Closing stale issue.
