### ISSUE TITLE
Fix packaging of maven artifact

### ISSUE THREAD

**Issue by vRallev** [facebook/conceal#27]
If you take a look at the .pom file in maven central, you'll notice that the packaging is 'aar.asc'. 

http://search.maven.org/#artifactdetails%7Ccom.facebook.conceal%7Cconceal%7C1.0.0%7Caar.asc

But it should be only 'aar'. I'm not sure what's causing this issue in your build.gradle file. You are using old build tools, that might be the reason. 

To fix the dependency in gradle I used: compile 'com.facebook.conceal:conceal:1.0.0@aar'

It works, but isn't that pretty. Otherwise the maven artifact works great!

**Comment by JosephEarl** [comment]
Please fix

**Comment by siyengar** [comment]
Thanks for the report @JosephEarl . Didn't know that this was happening. I will fix this.

**Comment by JosephEarl** [comment]
You can see more info on the accepted answer here http://stackoverflow.com/questions/22795455/transitive-dependencies-not-resolved-for-aar-library-using-gradle

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by anandpaithankar** [comment]
Has the fix been submitted for this issue? The latest Maven central pom.xml still shows packaging as "aar.asc". 

[pom.xml] (https://repo1.maven.org/maven2/com/facebook/conceal/conceal/1.0.1/conceal-1.0.1.pom) from Maven Central for v1.0.1

```xml
<modelVersion>4.0.0</modelVersion>
<groupId>com.facebook.conceal</groupId>
<artifactId>conceal</artifactId>
<version>1.0.1</version>
<packaging>aar.asc</packaging>
<name>Conceal</name>
```
Default configuration in the build.gradle is causing packaging to be used as "aar.asc" instead of "aar".

```gradle
configurations {
    archives {
        extendsFrom configurations.default
    }
}
```

Thanks

**Comment by carlossotelo** [comment]
This keeps being an issue... and a really nasty one.
Can this be fixed?
Thanks

**Comment by Blahartinger** [comment]
Bump, this is still an issue in 1.1.3. Can this please be fixed?

**Comment by waltarmour** [comment]
Bump again.

This is still an issue in 2.0.1.    It is definitely causing a bit of grief with dependency handling if Conceal is being used in another AAR project.

Apparently, simply removing the default configuration (as mentioned in Anand's comment, above) may resolve it.

**Comment by helios175** [comment]
Hi. We just uploaded version 2.0.2 with the fix to produce a AAR packaging type.
I could not yet try it on the same configuration app -> LibraryAAR -> ConcealAAR but you could give it a try.
