### ISSUE TITLE
How to use Conceal in my android application

### ISSUE THREAD

**Issue by thizisarun** [facebook/conceal#28]
Hi,
I want to integrate conceal in my application...Can you give me a sample android code...else explain me step by step...I am new for encryption and decryption

**Comment by abayomiAkanji** [comment]
Hi @siyengar I had a little issue with the code that decrypt the file.

```
while ((read = inputStream.read(buffer)) != -1) {
  out.write(buffer, 0, read);
}
```

The `out` object, where does it come from?I thought it could be a FileOutputStream object but unfortunately, It overrides the encrypted file. Kindly elucidate the `out` object.

Thanks in anticipation.
