### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [facebook/conceal#4]
I would like to point out that identifiers like "[```_JAVA_COM_FACEBOOK_CRYPTO_GCM_UTIL_```](https://github.com/facebook/conceal/blob/24a97da5aa8bd2ac497acfb878d16dbe8f669fa8/native/crypto/gcm_util.h#L1)" and "[```_JAVA_COM_FACEBOOK_CRYPTO_UTIL_```](https://github.com/facebook/conceal/blob/24a97da5aa8bd2ac497acfb878d16dbe8f669fa8/native/crypto/util.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
