### ISSUE TITLE
error on com.facebook.crypto.cipher.NativeGCMCipherException: decryptFinal

### ISSUE THREAD

**Issue by devilmac** [facebook/conceal#40]
Hi,

I'm using this library but when I call the decrypt method I get this error:
```
09-02 08:30:40.549: W/System.err(9205): com.facebook.crypto.cipher.NativeGCMCipherException: decryptFinal
09-02 08:30:40.549: W/System.err(9205): 	at com.facebook.crypto.cipher.NativeGCMCipher.decryptFinal(NativeGCMCipher.java:108)
09-02 08:30:40.549: W/System.err(9205): 	at com.facebook.crypto.streams.NativeGCMCipherInputStream.ensureTagValid(NativeGCMCipherInputStream.java:126)
09-02 08:30:40.549: W/System.err(9205): 	at com.facebook.crypto.streams.NativeGCMCipherInputStream.read(NativeGCMCipherInputStream.java:91)
09-02 08:30:40.549: W/System.err(9205): 	at com.facebook.crypto.streams.NativeGCMCipherInputStream.read(NativeGCMCipherInputStream.java:76)
09-02 08:30:40.549: W/System.err(9205): 	at com.facebook.crypto.Crypto.decrypt(Crypto.java:131)
09-02 08:30:40.549: W/System.err(9205): 	at com.example.sampleconceal.MainActivity.onCreate(MainActivity.java:46)
09-02 08:30:40.549: W/System.err(9205): 	at android.app.Activity.performCreate(Activity.java:5008)
09-02 08:30:40.549: W/System.err(9205): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
09-02 08:30:40.549: W/System.err(9205): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
09-02 08:30:40.549: W/System.err(9205): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
09-02 08:30:40.549: W/System.err(9205): 	at android.app.ActivityThread.access$600(ActivityThread.java:130)
09-02 08:30:40.549: W/System.err(9205): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
09-02 08:30:40.549: W/System.err(9205): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-02 08:30:40.549: W/System.err(9205): 	at android.os.Looper.loop(Looper.java:137)
09-02 08:30:40.549: W/System.err(9205): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
09-02 08:30:40.549: W/System.err(9205): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-02 08:30:40.549: W/System.err(9205): 	at java.lang.reflect.Method.invoke(Method.java:511)
09-02 08:30:40.549: W/System.err(9205): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
09-02 08:30:40.549: W/System.err(9205): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
09-02 08:30:40.549: W/System.err(9205): 	at dalvik.system.NativeStart.main(Native Method)
```

I'm using a Genymotion emulator to run my sample app.

**Comment by olaray** [comment]
@siyengar thank you for your response...I still havent gotten the hang of this problem...to answer your question...

yes i'm reading an encrypted file and this files was encrypted one a different device...so i plan on decrypting it on another...

Well, I am using different Crypto object to do encryption and decryption...hope this is not the problem.


as for the entity...aint it supposed to be the password i used in encrypting i'm supposed to pass?


My assumption, I'm thinking...only the application that did the encryption can only decrypt...please clearify

**Comment by siyengar** [comment]
I think I know the issue here. The problem there is the SharedPreferencesKeychain you're using. By default this generates a new key if there isn't one already the first time for the device.

You seem to require some custom behavior which requires the sender and receiver are sharing a key (so that the receiver can decrypt the content the sender sent). I'm not sure of your application, but you can definitely implement any scheme by using a custom Keychain which you pass to the Crypto object.

**Comment by olaray** [comment]
Great! thnks for these information...writing my own custom KeyChain solves the problem...Though, the appropriate value of the entity is not clear yet but i have a working solution right now

**Comment by siyengar** [comment]
For a description of entity check this issue out. https://github.com/facebook/conceal/issues/57

filename should be a good value for the entity.
