### ISSUE TITLE
Using Conceal with BitmapFactory.decode

### ISSUE THREAD

**Issue by kschults** [facebook/conceal#43]
Conceal does not work with the `BitmapFactory.decode` family of methods. Inside decode, `InputStream.skip` is called, which throws `NotImplementedException`. Writing images to a file works great, but reading fails. As a workaround, it is possible read them as a `ByteArrayInputStream`, then convert the `byte[]` to a bitmap, but it would be much cleaner if I could just pass the cipher stream to decodeBitmap.

**Comment by ericeche** [comment]
Any news about the encryption of  BitmapFactory.decode. If no news I can write my own repo and add this to your library

**Comment by siyengar** [comment]
Ya if you have time to implement this I'd be happy to accept a pull request. If you have any questions please let me know as well.

All we have to do in skip() is to read the bytes in like normal, but not supply them to the reader.

**Comment by mburman** [comment]
Finally got around to doing this https://github.com/facebook/conceal/pull/75

**Comment by ericeche** [comment]
Awsome!...good implementation

**Comment by helios175** [comment]
Merged #121 into master, implementing skip.
