### ISSUE TITLE
ClassNotFoundException Native Crash On Lollipop using Gradle/AAR

### ISSUE THREAD

**Issue by JaredBanyard** [facebook/conceal#47]
Trying to execute:
new Crypto(new SharedPrefsBackedKeyChain(context), new SystemNativeCryptoLibrary());

Results in:
A/art﹕ art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI GetFieldID called with pending exception 'java.lang.ClassNotFoundException' thrown in unknown throw location
A/art﹕ art/runtime/check_jni.cc:65]     in call to GetFieldID
A/art﹕ art/runtime/check_jni.cc:65]     from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String)

**Comment by disusered** [comment]
@JaredBanyard Do you mind sharing how you configured ProGuard? I'm getting the same issue, I'm not really an Android dev and would appreciate any pointers before I jump into debugging it on my own project!
