### ISSUE TITLE
Latest version on maven central have an unsafe version of OpenSSL

### ISSUE THREAD

**Issue by Snorlock** [facebook/conceal#51]
Im using gradle to import conceal.
compile 'com.facebook.conceal:conceal:1.0.0@aar'

Google now complains that im using openSSL 1.0.1e, which is unsafe.
This was upgraded for conceal in july:
https://github.com/facebook/conceal/commit/7d0ca9320b6fe0444375eb548cf089cf749bc107

But maven central repo has not been updated since may: http://search.maven.org/#search%7Cga%7C1%7Cconceal

When i run unzip -p YourApp.apk | strings | grep "OpenSSL", which google tells me to do.
It finds alot of OpenSSL, 1.0.1e strings in my apk package, which was the version coneal used before the upgrade in july.
Iv gone through the other libraries which are, dagger, otto and gson, and I believe they dont use openSSL.

So is there anything i can do to get conceal updated with the latest version through gradle?

**Comment by siyengar** [comment]
we haven't cut a new release yet. didn't realize people were getting complaints. As a temporary workaround you can build openssl from our repo directly. If you clone the repo, there are instructions on how to do that, and you can then use the artifacts directly in your lib folder of your app.

**Comment by niranjanr** [comment]
Hey @siyengar, do you have an approximate idea of when you will cut a new release? Thanks!

**Comment by siyengar** [comment]
Hey @niranjanr  ill have it out by tomorrow or the day after. We have all the moving parts ready now.

**Comment by siyengar** [comment]
https://github.com/facebook/conceal/pull/54

**Comment by siyengar** [comment]
sonatype has the latest version now, the changes should propagate to maven central in a bit. 

If you want to get it immediately, you can get the aar from sonatype (https://oss.sonatype.org/index.html#nexus-search;quick~conceal)  or you could wait for a little bit while sonatype propagates the latest version to maven central.

We haven't bumped the release version since it is an upgrade of the dependency rather than the library.

**Comment by Snorlock** [comment]
Thanks!

**Comment by niranjanr** [comment]
Thank you!

**Comment by Snorlock** [comment]
Im trying to update this. Im using gradle and compiling it with:

compile 'com.facebook.conceal:conceal:1.0.0@aar'
Im depending om mavenCentral()

Iv tried to delete the caches so that it will redownload the library, but still seem to get OpenSSL 1.0.1e.
Might have a pointer to what im doing wrong?

**Comment by siyengar** [comment]
I think what has happened is that when I upgraded the new version with the old version number, it broke maven's caching model. I'm going to try updating and bumping with a new version number so that we can  force maven to update.

**Comment by Snorlock** [comment]
Whats the latest news on this?

**Comment by siyengar** [comment]
I've uploaded a new version to 1.0.1 http://search.maven.org/#artifactdetails%7Ccom.facebook.conceal%7Cconceal%7C1.0.1%7Caar.asc. It has some minor changes to the class paths which are easily fixable once you upgrade.
