### ISSUE TITLE
BUCK file or README.MD outdated

### ISSUE THREAD

**Issue by hohnamkung** [facebook/conceal#52]
Because of https://github.com/facebook/conceal/issues/51, i'm trying to build master branch.
(I think master branch's openssl version already updated to 1.0.1h on https://github.com/facebook/conceal/commit/5f2492fe707ec753bb763949d2011d361cbacebc. Am i correct?)
However after 7b09a0287b3b680490d8f88b89166a81ca4d5e92 merged, BUCK command(`buck build :crypto`) does not work. 

I can build project if i move commit before https://github.com/facebook/conceal/commit/7b09a0287b3b680490d8f88b89166a81ca4d5e92.
But please fix BUCK file or build guide on README.MD

**Comment by siyengar** [comment]
Thanks, i've fixed the guide. Let me know if there's some other blockers in using it. 

For openssl we should have a new version up and running this week. I'm doing some tests on it.

**Comment by niranjanr** [comment]
Hey @siyengar, do you have an estimate of when you might be publishing an updated version of this to maven? I ran into the same problem of Google Play Store warnings and I am trying to decide between switching to building this myself as opposed to waiting for a week and just picking up the latest version published to maven. I would prefer the latter :). 

Thanks!

**Comment by siyengar** [comment]
@niranjanr I'll should probably be able to get to it this weekend.

**Comment by niranjanr** [comment]
Thank you! I really appreciate all the amazing work you have been doing on
this project.
