### ISSUE TITLE
Gradle Import Not Importing OpenSSL Fixes?

### ISSUE THREAD

**Issue by JaredBanyard** [facebook/conceal#58]
Google is still reporting that I am referencing vulnerable OpenSSL versions.  Does the documented import method actually import recent fixes?  If you guys are updating OpenSSL and iterating, why isn't the version changing?  Currently importing as follows:

compile 'com.facebook.conceal:conceal:1.0.0@aar'

**Comment by siyengar** [comment]
Like I mentioned in the task, the openssl only updates the dependency, so it doesn't warrant a version bump.  You might have a cached maven artifact locally, could you try deleting your local copy and refresh from maven central?

**Comment by JaredBanyard** [comment]
I assume you guys already implement a form of PRNGFixes.java from the Android developer blog?  That references a native OpenSSL implementation and could be the source of this as well.  Do I have any reason of implementing PRNGFixes if you guys are?

**Comment by siyengar** [comment]
We do, however I think google play looks like libraries for it and not pure strings, otherwise every comment would be flagged.

You don't need to unless you use SecureRandom before initializing conceal.

I'll close this out. Please feel free to reopen if you're still facing problems.

**Comment by JaredBanyard** [comment]
In case you haven't seen the notice, it looks like this:
Your app is statically linking against a version of OpenSSL that has multiple security vulnerabilities. You should update OpenSSL as soon as possible.
The vulnerabilities were addressed in OpenSSL versions beginning with 1.0.1h, 1.0.0m, and 0.9.8za. To confirm your OpenSSL version, you can do a grep via ("$ unzip -p YourApp.apk | strings | grep "OpenSSL""). For more information about the vulnerability, please consult http://www.openssl.org/news/secadv_20140605.txt.
To confirm that you've upgraded correctly, upload the updated version to the Developer Console and check back after five hours.
Please note, while it's unclear whether these specific issues affect your application, applications with vulnerabilities that expose users to risk of compromise may be considered "dangerous products" and subject to removal from Google Play.

**Comment by JaredBanyard** [comment]
@siyengar I have wiped out the workspaces and am still getting the warning from Google that the application is statically linking against a version of OpenSSL that has multiple security vulnerabilities.

**Comment by siyengar** [comment]
@JaredBanyard thanks for reporting that again. I'll try to upload a small app to google play to reproduce. Expect a response by the day after tomorrow.
