### ISSUE TITLE
May update concel in maven central

### ISSUE THREAD

**Issue by Qinwroks** [facebook/conceal#60]
keep up with github master,maybe?

**Comment by siyengar** [comment]
@Qinwroks I see the Feb 2015 update in maven central http://search.maven.org/#search%7Cga%7C1%7Cconceal. It might be possible your local cache is holding on to the may update. Can you try clearing your local cache or point me to the place you see the May update

**Comment by Qinwroks** [comment]
@siyengar thanks.
