### ISSUE TITLE
crypto.jar missing

### ISSUE THREAD

**Issue by andynugent** [facebook/conceal#61]
According to http://facebook.github.io/conceal/documentation/ I should:

"Add a dependency to crypto.jar from java code using your favorite dependency management system, and drop the .so files in libs.zip into your libs/ folder."

Except crypto.jar has been removed, and replaced with conceal_android.jar and libconceal.jar.

This was done in SVN revision 70:

Revision: 70
Author: subodh.iyengar
Date: 10 February 2015 12:34:56 PM
Message:
update artefacts
----
Added : /branches/gh-pages/downloads/conceal_android.jar
Deleted : /branches/gh-pages/downloads/crypto.jar
Added : /branches/gh-pages/downloads/libconceal.jar
Modified : /branches/gh-pages/downloads/libs.zip

**Comment by andynugent** [comment]
From looking at the content of the jar files, it looks like the documentation just needs updating to reference the newly named jar files.

**Comment by siyengar** [comment]
Thanks @andynugent will update.
