### ISSUE TITLE
Increment version number when you make changes

### ISSUE THREAD

**Issue by cv-lr** [facebook/conceal#62]
Your current deployment process to Maven Central appears to be seriously flawed. Since you keep re-releasing as version 1.0.0, it breaks Maven's caching behaviour - people with cached versions of the library won't get the updates.

I ran into this when doing a build on a new machine and getting a compile error since you've changed the package structure.

I'm not the first person to run into this - e.g. #60, #58 - and I'm sure others will too. It also likely means a lot of devs out there using Maven/Gradle aren't getting the latest version.

**Comment by siyengar** [comment]
I'm not a maven expert and assumed that maven would reasonable cache based on a hash an not version number which was a bad assumption. The reason I didn't change the version number was because the major change was basically a third-party library upgrade. Since then, we've updated other places as well.

It seems that maven is forcing my hand here and I'll bump the version to the new version number and upload a new binary. Thanks for the report.

**Comment by JaredBanyard** [comment]
@siyengar I'm assuming this will solve the OpenSSL issue as well?

**Comment by siyengar** [comment]
Yes it will @JaredBanyard

**Comment by JaredBanyard** [comment]
Great, I look forward to the resolution!  Thanks for your time on this.

**Comment by JaredBanyard** [comment]
@siyengar Any progress on this?  I would really like to patch the vulnerable version of OpenSSL.

**Comment by siyengar** [comment]
I've uploaded a new version to 1.0.1 http://search.maven.org/#artifactdetails%7Ccom.facebook.conceal%7Cconceal%7C1.0.1%7Caar.asc. Could you verify that this works for you @JaredBanyard

**Comment by JaredBanyard** [comment]
@siyengar The package name for the SharedPrefsBackedKeyChain changed from  com.facebook.crypto.keychain.SharedPrefsBackedKeyChain to  com.facebook.android.crypto.keychain.SharedPrefsBackedKeyChain for some reason.  But after fixing the import, it compiles and functions. Was that expected?  I will update the APK and report on the play store notices.

**Comment by siyengar** [comment]
@JaredBanyard  yes, since this is a new release, I have improved some of the namespacing of packages. Thanks for being patient.

**Comment by siyengar** [comment]
@JaredBanyard did that fix work for you.

**Comment by JaredBanyard** [comment]
@siyengar Yes! The warning from Google about the vulnerable OpenSSL version has gone away! Thanks for your time on this!
