### ISSUE TITLE
Safe guard the Cipher key stored in Shared Preferences

### ISSUE THREAD

**Issue by sasindroid** [facebook/conceal#64]
Hello, Thanks for such a wonderful library at the first place.

I am planning to use the conceal library for my live app. My purpose is to store user data encrypted in the device. From your documentation, I understand the Cipher key is being stored as Shared Preferences (under crypto.xml - with content below).

<?xml version="1.0" encoding="UTF-8" standalone="true"?>
-<map>
<string name="cipher_key">******************************* </string>
</map>

My issue is to keep the cipher_key secure enough. On a rooted phone the Shared Preferences is easily accessible and its easy for a malicious app or hacker to get hold of the key and decrypt my user data.

Please advise on how to store the "cipher_key" securely within the app. I would like to use this without the user consent.

My app supports android versions 4.0 and above. Please guide.

**Comment by sasindroid** [comment]
I am sorry if this has already been answered, if so please guide me there. 
The "conceal" documentation talks about the MODE_PRIVATE which seems to be perfectly fine on an unrooted device. In case of a rooted device, the Shared Preferences are compromised.

**Comment by siyengar** [comment]
@sasindroid in the case of a rooted device even the apps memory is not safe. Thus secrets can be recovered one way or another. Thus we assume the threat model that the attacker cannot access the users local data partition. There is no way to protect the app if the device is rooted and the user has given root access to a malicious app.
