### ISSUE TITLE
Conceal Help

### ISSUE THREAD

**Issue by samsoft00** [facebook/conceal#65]
I'm currently working on a project and i've been tasked to make sure the contents/data inside the apk is secure from been accessed by users, i'm been research for a couple of days now and i finally find this library, please do you think this will provide solution for this task (Encrypting the data, so user will not have access to it), if not? is there any alternative...? (i'll appreciate your suggestion). lastly. To encrypt data with this library? data must be on SD card or inside the internal memory?

**Comment by siyengar** [comment]
Any data you give to the user in the APK and that you need to use locally for other purposes will always be accessible to the user, you can't prevent it. With conceal you can encrypt data anywhere, but encrypting data in the internal memory does not seem that useful to me. I don't know what your application is or what your threat model is, so I can't make specific recommendations.

**Comment by samsoft00** [comment]
@siyengar appreciate, actually the data to be encrypted is bundle with the apk and its upto 400MB which reside on assets folder, no plan to put it on Google play because it will be distribute on a android phone for an organisation from the factory. i need to find a way to encrypt the data, so when user have access to it... it'll be useless because this are high level data that must be secure and they want this data offline. I know any data given to the user in the apk can be accessed but i need to find a way to make the data useless when they have access to it.. only the application will be able to read it!
