### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by wsidell** [facebook/conceal#66]
Is there any chance that this library will also be available on iOS in the near future?

**Comment by siyengar** [comment]
@wsidell not immediately. We'll look into it if there are enough requests from the community.

**Comment by johndarsena** [comment]
I'm also looking for this library on iOS. Would like to be able to share a file between iOS and Android in a consistent encrypted file format.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by hoonkai** [comment]
+1 Would be great if there's iOS support.

**Comment by dev0x10** [comment]
+1

**Comment by BoydYang** [comment]
+1, I think it should be a C/C++ version. Conceal 2.0. When will cocneal 2.0 be released?

**Comment by helios175** [comment]
There's a C++ port now in Conceal 2.0.
People in iOS told me it should not be that difficult to use it (or create wrappers) from iOS. But I cannot involve in that project myself.
