### ISSUE TITLE
64-Bit Binaries & Gradle Builds

### ISSUE THREAD

**Issue by JaredBanyard** [facebook/conceal#67]
There are none! I am going to try compiling the code by hand in the mean time.  Help, this is crashing apps in the field!

**Comment by siyengar** [comment]
do you know which device this is crashing on?

**Comment by JaredBanyard** [comment]
@siyengar HTC One M9 so far.  But the error is that /lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libconceal.so".  We need arm64-v8a x86_64 added to the Application.mk file in the native code.

**Comment by JaredBanyard** [comment]
@siyengar oops didnt mean to close.

**Comment by siyengar** [comment]
Didn't realize that we have people using 64 bit devices already. That's great. Feel free to send a pull request as well for this.

**Comment by JaredBanyard** [comment]
Yeah I will send one as soon as I get it building

**Comment by JaredBanyard** [comment]
@siyengar So you guys are building OpenSSL externally and importing the `.a` files? Obviously we will need the 64-bit versions to move forward.  I will try building it myself, but I'm not sure how you guys want to move forward on this.

**Comment by siyengar** [comment]
@JaredBanyard thanks for reminding me. Ya we recently changed the integration process so that we could keep up with the latest version quicker. I will do the upgrade.

Is the problem here that the libs are not loading, or you're crashing after the libs load? Do you have any  another 64 bit library in your binary?

**Comment by JaredBanyard** [comment]
@siyengar I pulled in some 64-bit versions, it seems that there are a few pointer casts that aren't going to work in the JNI.  I just ran into this with SQLite code.  I am part of the way through fixing them at the moment, but I am concerned about the `GCM_JNI_CTX` and `HMAC_JNI_CTX` structs.  I am going to do a little more testing and see what I can come up with.

**Comment by siyengar** [comment]
are you packaging other 64 bit libraries in your binary when this error occurs.

**Comment by JaredBanyard** [comment]
While trying to build Conceal? Yes, I pulled in the AOSP x86_64 and arm64 libcrypto.a to test the app's compatibility.  When running Buck I get issues with all the Get and Set JNI CTX methods because they are casting to `jint`.  As far as my app goes, I do have other 64-bit libraries, if that is what you are asking.

**Comment by siyengar** [comment]
yup that's what i'm asking, whether you have other 64-bit libraries. When android sees even one library in your apk with the primary ABI of the phone it ignores all other libraries. 

I think android 64 bit should still have support for 32 bit libs. You should be able to test whether the 32 bit library loads and works by removing the other 64 bit libraries for a test case.

**Comment by JaredBanyard** [comment]
@siyengar I was wondering that myself .. I tracked it down, we have a gradle import that has apparently has binaries for all the architectures.  If I comment that library and its associated code, conceal works again because the whole app switches to 32-bit compatibility mode.  Not exactly the best solution.

**Comment by JaredBanyard** [comment]
@siyengar it seems all the JNI code needs to be made portable.  Probably using a combination of `intptr_t`  and `jlong`.  gcm.*, hmac.*,gcm_util.*, hmac_util.*, util.*, etc...

**Comment by JaredBanyard** [comment]
@siyengar Yeah I will go ahead and kill my 64-bit components for now.  When do you think you guys will be able to get 64-bit openssl binaries and fix the pointer casting?

**Comment by siyengar** [comment]
@JaredBanyard i'll start working on it this week. Expect support for 64 bit by next week and latest by the week after next.

**Comment by Fax3D** [comment]
Hi @siyengar ,
i've the same problem on a project on which I work: running on Samsun Galaxy S6 (and also on HTC M9) i got the same error about 64bit library not founded.
Because I work for an important italian company (Telecom Italia) on a very important App (you can see it here: https://play.google.com/store/apps/details?id=it.telecomitalia.centoottantasette), i would like to fix this issue as soon as possible :)

Thanks!

Fabio

**Comment by JaredBanyard** [comment]
@Fax3D Again, the quick fix is to remove all 64-bit binaries from all libraries.  This includes any being pulled down in Gradle/Maven artifacts.  This will allow the app to run in 32-bit compatibility mode until the 64-bit binaries are done.  I had one Gradle import that I had to get the `.aar` file, open it in an archive manager and delete the 64-bit binaries out of it.  The 64-bit binaries are only optimized to run faster on 64-bit devices.

**Comment by Fax3D** [comment]
Thanks for your reply @JaredBanyard 
This quick fix works fine, very good!

**Comment by JaredBanyard** [comment]
@siyengar any progress on this?  Thanks!

**Comment by aaalaniz** [comment]
Is there any progress on this? I have a hard dependency that includes 64 bit support for arm and intel, so the workaround stated does not apply. Thanks!

**Comment by ashughes** [comment]
@siyengar Just wanted to put in my +1 for this as well. Sounds like it's being worked on. Any update on the progress?

**Comment by siyengar** [comment]
Hey guys, sorry I had been busy with working on some other stuff. Will work on this, this week.

**Comment by kolencherry** [comment]
@aaalaniz and I managed to get it working on armv8 and can provide the patchset+static libs for the JNI code and the Java code. Unfortunately, we patched and built the openssl libs by hand, so that side of things will need to be implemented by someone.

**Comment by aaalaniz** [comment]
PR is available at https://github.com/facebook/conceal/pull/73

**Comment by JaredBanyard** [comment]
@siyengar thoughts?

**Comment by JaredBanyard** [comment]
@siyengar Can you please merge in this code and make a new gradle artifact available?  Thanks!

**Comment by kobakei** [comment]
Any update about this issue?

**Comment by JaredBanyard** [comment]
@kobakei Great question.. seems like @siyengar has gone missing ...

**Comment by aaalaniz** [comment]
@JaredBanyard @kobakei ...i have an aar if you all are interested

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by instantiator** [comment]
@aaalaniz yes please!

**Comment by aaalaniz** [comment]
Reach out to me via email and i'll provide

**Comment by burcsade** [comment]
It has been almost 6 months and there is still no sign of a 64 bit lib? Our app fails on 64bit devices and we have no option but to revert to using some other solution now.

**Comment by MangeshKadam** [comment]
@aaalaniz - can you provide me aar file? I need this..thanks in advance.

**Comment by siyengar** [comment]
1.0.3 has just been released on mvn central which should fix the issue with updated libs

**Comment by cotfas** [comment]
Hello guys,

I`ve opened an issue request at

https://github.com/facebook/conceal/issues/119


Can someone share with me the compiled binaries for 64bit ? 

I`m not able to compile myself :(

Thanks in advance
