### ISSUE TITLE
Unreadable crypted files after upgrading conceal

### ISSUE THREAD

**Issue by Fax3D** [facebook/conceal#68]
Hi,

I got this error after upgrading (got latest version from maven) from an older version of conceal:
java.io.IOException: Unexpected crypto version -30

So my old saved crypted file are now unreadable!
How can I fix this problem?

Thanks.

Fabio

**Comment by siyengar** [comment]
We haven't changed the encryption format at all between 1.0.0 and 1.0.1. Which version were you using initially @Fax3D ?

**Comment by Fax3D** [comment]
@siyengar Previous version was really old, nearly february 2014. 
This problem occours even if i upgrade from the older version (02/2014) to a version builded in 05/2014.

But if I left crypto.jar from 02/2014 with *.so from a newer build (07/2014) work fine, and i needed to do so last year, to fix the famous heartbleed openssl issue.
Maybe a problem only with some code upgrade in crypto.jar?

Now I'm trying again to upgrade with the latest version from maven... and I got the error above.

Thanks.

Fabio

**Comment by siyengar** [comment]
Could you point me to a commit hash from which you used the code previously + the current commit hash. That would be more helpful to track down any issue

**Comment by Fax3D** [comment]
The first version I used was taken from your commits on Feb 6, 2014 (3f809ccb974cf340a344a5146590f6a606f93cbb)

Now in my working project, I use the same crypto.jar of Feb 6, 2014, but with *.so from your commits on Jul 3, 2014 (439be4b4f4e2cd2af1b9c491f0113cd94d4857a0)

I'm trying to update this situation with the latest commit, using AndroidStudio and Maven (com.facebook.conceal:conceal:1.0.1@aar)

Hope this helps!

Thnaks.

Fabio

**Comment by siyengar** [comment]
I'll take a look, and get back to you ASAP. Thanks for the additional info.

**Comment by Fax3D** [comment]
@siyengar Thanks for help, waiting for your feedback...

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by helios175** [comment]
Closing stale issue.
