### ISSUE TITLE
Is Crypto threadsafe? 

### ISSUE THREAD

**Issue by vijayrawatsan** [facebook/conceal#69]
Can I use single instance of Crypto in my whole application?

**Comment by siyengar** [comment]
Provided the KeyChain you pass to is thread safe, it should be thread safe.

**Comment by vijayrawatsan** [comment]
Is SharedPrefsBackedKeyChain thread safe?

**Comment by siyengar** [comment]
I just noticed a bug in SharedPrefsBackedKeyChain that makes it not completely thread safe. I'm going to put up a fix for it.

**Comment by takara727** [comment]
Is SharedPrefsBackedKeyChain thread safe now?

**Comment by ninovanhooff** [comment]
bump
