### ISSUE TITLE
Incorrect implementation of Closeable doesn't allow double closing, instead throws IllegalStateException

### ISSUE THREAD

**Issue by joshzana** [facebook/conceal#71]
I'm adapting some existing code to write from the network to a CipherOutputStream instead of a FileOutputStream.  The existing code wraps the provided stream in a BufferedOutputStream and writes to that.  It then closes the BufferedOutputStream, followed by closing the FileOutputStream.  Whether or not this is necessary, this is supposed to be safe according to the Closeable javadoc:

	/**
	 * An {@code AutoCloseable} whose close method may throw an {@link IOException}.
	 */
	public interface Closeable extends AutoCloseable {

	    /**
	     * Closes the object and release any system resources it holds.
	     *
	     * <p>Although only the first call has any effect, it is safe to call close
	     * multiple times on the same object. This is more lenient than the
	     * overridden {@code AutoCloseable.close()}, which may be called at most
	     * once.
	     */
	    void close() throws IOException;
	}

Unfortunately, calling close twice on a CipherOutputStream throws:

    java.lang.IllegalStateException: Cipher has not been finalized
            at com.facebook.crypto.util.Assertions.checkState(Assertions.java:23)
            at com.facebook.crypto.cipher.NativeGCMCipher.ensureInFinalizedState(NativeGCMCipher.java:138)
            at com.facebook.crypto.cipher.NativeGCMCipher.destroy(NativeGCMCipher.java:115)
            at com.facebook.crypto.streams.NativeGCMCipherOutputStream.close(NativeGCMCipherOutputStream.java:52)

One potential fix here is to have destroy() move to a new state "destroyed" and allow that in future calls to destroy()

**Comment by siyengar** [comment]
Fair enough. Since this is a specific property required of the stream rather than the cipher object itself, it might be easy enough to ignore the second close() call to NativeGCMCipherOutputStream.

**Comment by mburman** [comment]
Should be fixed! Thanks @bailan
