### ISSUE TITLE
Cannot instantiate the type KeyChain

### ISSUE THREAD

**Issue by deepak-goodmethodsglobal** [facebook/conceal#78]
I tried to use facebook conceal encryption technique in my Android app.
I ended up with the following error when I tried to initiate KeyChain.
:- Cannot instantiate the type KeyChain.
I have added the following headers :- 
import com.facebook.crypto.Crypto;
import com.facebook.crypto.keychain.KeyChain;
import com.facebook.crypto.util.NativeCryptoLibrary;
import com.facebook.crypto.util.SystemNativeCryptoLibrary;

**Comment by mburman** [comment]
KeyChain is an interface and you can't instantiate interfaces. You should instantiate SharedPrefsBackedKeyChain instead.

**Comment by deepak-goodmethodsglobal** [comment]
Thanks mburman.
I tried the following code :- 
Crypto crypto = new Crypto(new SharedPrefsBackedKeyChain(getApplicationContext()),new SystemNativeCryptoLibrary());
But I am getting an error as "SharedPrefsBackedKeyChain cannot be resolved to a type".
Is there any header I need to include ?

**Comment by mburman** [comment]
Sounds like an eclipse issue... Try Project --> clean.

**Comment by deepak-goodmethodsglobal** [comment]
Thanks dude.
I have closed and opened the eclipse, build and clean the project, but still it's showing the same errror.
![error](https://cloud.githubusercontent.com/assets/12610499/7906758/c99d0aac-084d-11e5-9f52-e98f21db8cf6.jpg)

**Comment by mburman** [comment]
Try importing it? Doesn't look like you are
