### ISSUE TITLE
OutOfMemoryException error

### ISSUE THREAD

**Issue by vikalppatelce** [facebook/conceal#79]
I've tried large files(10MB) encryption with Conceal which did works perfectly fine with combination of your document and little of "FileUtils.readFileToByteArray(mPlainFile)"(Commons IO utils). 

But Whenever I'm trying to decrypt the same file it turns out to be "OutOfMemoryException" as we've to take the whole encrypted file in Device Memory(runnning 2.3.7 android it crashes after taking 8MB in memory). Is there any other solution from which we can did encryption and decryption (10 MB max.) with lower devices too?

**Comment by vikalppatelce** [comment]
Here's my implementation which i'm executing while encrypting and decrypting which no more leads to OutOfMemoryException.

Encryption :

fileStream = new BufferedOutputStream(new FileOutputStream(mEncryptedFile));
OutputStream outputStream;
outputStream = crypto.getCipherOutputStream(fileStream, entity);
int read;
byte[] buffer = new byte[1024];
BufferedInputStream  bis = new BufferedInputStream(newFileInputStream(mPlainFile));
while ((read = bis.read(buffer)) != -1) {
       outputStream.write(buffer, 0, read);
    }
outputStream.close();
bis.close();

Decryption :

InputStream inputStream;
inputStream = crypto.getCipherInputStream(fileStream, entity);
ByteArrayOutputStream out = new ByteArrayOutputStream();
OutputStream outputStream = new FileOutputStream(mDecryptedFile);
BufferedInputStream bis = new BufferedInputStream(inputStream);
int mRead;
byte[] mBuffer = new byte[1024];
while ((mRead = bis.read(mBuffer)) != -1) {
   outputStream.write(mBuffer, 0, mRead);
    }
bis.close();
out.writeTo(outputStream);
inputStream.close();
outputStream.close();
out.close();

**Comment by TapanM** [comment]
Not able to solve with above code..App is crashing
