### ISSUE TITLE
Can NativeGCMInputStream start reading from a random position?

### ISSUE THREAD

**Issue by gitanuj** [facebook/conceal#80]
Crypto.getCipherInputStream() expects that the InputStream starts with 'cryptoVersion' bytes etc. Is there a way I can supply the 'metadata' (cryptoVersion, cipherID & IV) and use an InputStream starting from a random position as upstream?

I want to randomly seek within an encrypted data blob. Is there any recommended way to go around this?

**Comment by mburman** [comment]
I have a pull request out (https://github.com/facebook/conceal/pull/75) which should let you skip any number of bytes.

**Comment by gitanuj** [comment]
@mburman Because skip() internally reads all the bytes to be skipped, wouldn't that be expensive if I want to seek within a large file?

**Comment by mburman** [comment]
Yeah, but we need to read all the bytes to ensure that the authentication tag matches at the end so I don't really see a way of seeking without skip()

**Comment by helios175** [comment]
Pull request #121 implements skip. #75 was closed without merging.
