### ISSUE TITLE
link to crypto.jar bad

### ISSUE THREAD

**Issue by bgrayburn** [facebook/conceal#88]
link on https://facebook.github.io/conceal/  to crypto.jar is bad. Is the only way to obtain crypto.jar through buck?

**Comment by G33KS44n** [comment]
crypto.jar isn't downloaded ...

**Comment by bgrayburn** [comment]
?

**Comment by G33KS44n** [comment]
I can't download the crypto.jar

**Comment by mburman** [comment]
Just submitted a pull request to fix this. Meanwhile, you should be able to download the correct jar here http://facebook.github.io/conceal/documentation/

**Comment by G33KS44n** [comment]
@mburman  than you
