### ISSUE TITLE
Android 6.0 Marshmallow - CryptoInitializationException: java.lang.UnsatisfiedLinkError: dlopen failed; has text relocations

### ISSUE THREAD

**Issue by mittt** [facebook/conceal#90]
I get the error below on Android 6.0 in emulator (tested on both 64bit and 32bit). The lib does not work there. 

` com.facebook.crypto.exception.CryptoInitializationException: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.NEWmobiAudit-2/lib/x86/libconceal.so: has text relocations
 at com.facebook.crypto.util.SystemNativeCryptoLibrary.ensureCryptoLoaded(SystemNativeCryptoLibrary.java:40)
 at com.facebook.crypto.cipher.NativeGCMCipher.encryptInit(NativeGCMCipher.java:54)
 at com.facebook.crypto.CipherHelper.getCipherOutputStream(CipherHelper.java:38)
 at com.facebook.crypto.Crypto.encrypt(Crypto.java:102)`

I think I'm using the latest version -     compile 'com.facebook.conceal:conceal:1.0.1@aar'.

**Comment by mittt** [comment]
Forgot to mention, this only happens when the app is build with the latest build tool, targeting android 6, and with updated support libs. I tested the store version of our app and it work, fine.

**Comment by adyach** [comment]
https://code.google.com/p/android-developer-preview/issues/detail?id=3028

**Comment by rfreedman** [comment]
This is currently keeping us from moving our app to full API 23 compatibility - we're running with targetSdkVersion 22 just so that Conceal continues to work. Surely, FaceBook is having this same issue? Can we please get this fixed and released?

**Comment by Winghin2517** [comment]
Hello. Confirmed that I'm also experiencing this error  on API 23. This is also preventing me from using the Conceal library with my app on API 23. Please fix.

**Comment by MangeshKadam** [comment]
please compile your native code with ndk-r10e. Because I am also using this library and compile SDK version is 23. It working fine in my app.

**Comment by Winghin2517** [comment]
Hello - I'm not using the native code though - I'm using the maven repo here: 'com.facebook.conceal:conceal:1.0.1'

**Comment by matthewrice345** [comment]
Same error with v23.

**Comment by MangeshKadam** [comment]
can you check cpu/abi of your emulator? Try Android 6.0 emulator with armeabi or armeabi-v7a. I did checked on Nexus 6 marshmallow with armeabi-v7a cpu-abi. Its working fine.

**Comment by siyengar** [comment]
I think this might be addressed by https://github.com/facebook/conceal/pull/101

**Comment by Winghin2517** [comment]
I can confirm that this error went away on API 23 with the build version below:

    compile 'com.facebook.conceal:conceal:1.1.2@aar'

**Comment by helios175** [comment]
The text relocations issue was fixed when we added the option -fPIC (position independent code) to the compiling of the OpenSSL library. native/third-party/Makefile. Also an instrumentation test to be run in an API 23 emulator was added.

This is effectively included under 1.1.2.
