### ISSUE TITLE
 com.facebook.crypto.cipher.NativeGCMCipherException: The message could not be decrypted successfully.It has either been tampered with or the wrong resource is being decrypted

### ISSUE THREAD

**Issue by ManzzBaria** [facebook/conceal#91]
Hi i am geting Exception while decryption file....
i m getting error when i m clear data or uninstall  app and install again and try to decrypte a image which encrypted before clear data or uninstall app.
i am showing below message:
"com.facebook.crypto.cipher.NativeGCMCipherException: The message could not be decrypted successfully.It has either been tampered with or the wrong resource is being decrypted."

please help me to solve this problem.
i m waiting for replay

**Comment by mburman** [comment]
This is pretty vague. Can you post the code you're using to encrypt/decrypt?

**Comment by ManzzBaria** [comment]
Now, i am clear that when we Clear Data (Clear Preference) of app and then try to decrypt a image which already encrypted before clear preference, its not working.

**Comment by instantiator** [comment]
Manzz are you using the same entity you used to encrypt the data? The message you're seeing means the checksums in the stream don't agree with what conceal was expecting.

**Comment by ManzzBaria** [comment]
Yes, I am using same Entity...
here is my code for encrypt/decrypt.

public static void encryptionFile(String oldPath, String newPath, Context context) {
        try {
	    File fileOld = new File(oldPath);
            String directory = newPath.substring(0,
                    newPath.lastIndexOf('/'));
            File enPath = new File(newPath);
            Crypto crypto = new Crypto(new SharedPrefsBackedKeyChain(context),
                    new SystemNativeCryptoLibrary());
            if (!crypto.isAvailable()) {
                return;
            }
            OutputStream fileStream = new BufferedOutputStream(
                    new FileOutputStream(enPath));
            OutputStream outputStream = crypto.getCipherOutputStream(
                    fileStream, new Entity(Global.PASSWORD));
            outputStream.write(fileToBytes(fileOld));
            outputStream.close();
            fileOld.delete();

        } catch (Exception e) {
            Log.e("encryptionFile", "Exception: " + e.toString());
        }
    }


  public static void decryptionFile(String oldPath, String filePath, Context context) {
        try 
	{
            Crypto crypto = new Crypto(new SharedPrefsBackedKeyChain(context),
                    new SystemNativeCryptoLibrary());
            ContextWrapper cw = new ContextWrapper(context);
            File file = new File(filePath);
            FileInputStream fileStream = new FileInputStream(file);
            InputStream inputStream = crypto.getCipherInputStream(fileStream,
                    new Entity(Global.PASSWORD));
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            int read;
            byte[] buffer = new byte[1024];
            	while ((read = inputStream.read(buffer)) != -1) 
		{
                	out.write(buffer, 0, read);
           	}
            inputStream.close();
            writeFile(out.toByteArray(), oldPath);
            file.delete();
            
        } catch (Exception e) {
            // TODO: handle exception
            Log.e("decryptionFile", "Exception: " + e.toString());
        }

    }

**Comment by ranjan000** [comment]
I am getting the same problem. Any solution?

**Comment by instantiator** [comment]
Sorry - I can't see what's wrong in your code - so here's what I'm doing, which seems to work. It doesn't seem that far removed from what you're doing though...

To write -- passing in an InputStream to read from, and a File object as the target, I'm doing this:
```
Crypto crypto = getCrypto();
FileOutputStream fileOut = context.openFileOutput(file.getName(), Context.MODE_PRIVATE);
Entity entity = new Entity(file.getName());
OutputStream out = crypto.getCipherOutputStream(outStream, entity);
int read;
int writ = 0;
byte[] buffer = new byte[1024];
while ((read = inStream.read(buffer)) != -1) {
  out.write(buffer, 0, read);
  writ += read;
}
out.close();
```
Note that `writ` reports how many plaintext bytes were recorded, not the size of the encrypted data. I've not drilled down in to `getCrypto` as I don't think it's essential, but I'm using a custom keychain.

To read -- from a given file:
```
Crypto crypto = getCrypto();
FileInputStream fileStream = context.openFileInput(file.getName());
Entity entity = createEntity(file.getName());
InputStream inputStream = crypto.getCipherInputStream(fileStream, entity);
```

It is important to read to the end of the file so that the crypto can do its checksum (that's when the exception will be thrown if it doesn't like it) -- but I think you're doing that. Here's my read code, where I'm effectively reading from the InputStream and writing straight into a ByteArrayOutputStream.
```
protected byte[] readData(InputStream data) {
  try {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    byte[] buffer = new byte[1024];
    int read;
    while ((read = data.read(buffer, 0, buffer.length)) != -1) {
      byteStream.write(buffer, 0, read);
    }
    data.close();
    return byteStream.toByteArray();

  } catch (Exception e) {
    return null; // or log the exception
  }
}
```

**Comment by ranjan000** [comment]
You'll need to modify SharedPrefsBackedKeyChain. Either save mCipherKey and mMacKey on a file or on server. Modify generateAndSaveKey not to save on sharedpreference. Next time if you'll get these two keys not available, restore these two from file or from server whatever your logic.

**Comment by Alok-Sharma** [comment]
Same problem here. If you try to decrypt after clearing your apps data, then the decryption will fail. Also, if you try to decrypt on a different device, than from where you encrypted the data, then also the decryption will fail. This seems wrong, but I may be incorrect in assuming so.

**Comment by saqada** [comment]
Alok-Sharma, you are absolutely right.

**Comment by sinha-abhishek** [comment]
By default you would be using SharedPrefsBackedKeyChain, which keeps the key in preferences, so if you clear app data the pref will be gone and thus file cannot be decrypted as it seems to be generating a new secure Random in case prefs is not there, which is not same as the key which you used to encrypt. I suppose you can implement  custom KeyChain, wherein you can handle the key generation logic.

**Comment by helios175** [comment]
Indeed the problem is in the KeyChain.
Entity is not a password, just some public-known identification of the file to avoid swapping valid encrypted files (and make File2 replace File1 without you knowing)
