### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by JaredBanyard** [facebook/conceal#92]
Has this project been abandoned?

**Comment by mburman** [comment]
Hey @JaredBanyard, I apologize for the lack of activity here. @siyengar and I have been pretty busy at Facebook over the last few months. We have a plan for things we want to accomplish/improve with regards to Conceal and you should see some love towards this pretty soon. In the meantime, feel free to send in pull requests for features you'd like to add.

**Comment by JaredBanyard** [comment]
Still seems like no progress
