### ISSUE TITLE
Couldn't find "libconceal.so"

### ISSUE THREAD

**Issue by punitshah89** [facebook/conceal#96]
Not able to load libconceal library.

Running on Samsung Galaxy Tab 4.

Android OS version: 5.0.2.

Check below stack trace for more information.

<b>Steps took to solve issues</b>
<ul>
<li> Added .so file in .aar module libs folder</li>
<li> Added .so file in app module libs folder</li>
</ul>

Stack Trace
_________________________________
09-23 16:15:15.399 9830-9830/co.example W/System.err: com.facebook.crypto.exception.CryptoInitializationException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/co.example-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libconceal.so"
09-23 16:15:15.399 9830-9830/co.example W/System.err:     at com.facebook.crypto.util.SystemNativeCryptoLibrary.ensureCryptoLoaded(SystemNativeCryptoLibrary.java:40)
09-23 16:15:15.399 9830-9830/co.example W/System.err:     at com.facebook.crypto.cipher.NativeGCMCipher.encryptInit(NativeGCMCipher.java:54)
09-23 16:15:15.399 9830-9830/co.example W/System.err:     at com.facebook.crypto.CipherHelper.getCipherOutputStream(CipherHelper.java:38)
09-23 16:15:15.399 9830-9830/co.example W/System.err:     at com.facebook.crypto.Crypto.encrypt(Crypto.java:102)
09-23 16:15:15.399 9830-9830/co.example W/System.err:     at co.example.helpers.Helper.encrypt(Helper.java:77)
09-23 16:15:15.409 9830-9830/co.example W/System.err:     at com.example.common.fragments.SignInFragment.onCreate(SignInFragment.java:56)
09-23 16:15:15.409 9830-9830/co.example W/System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:833)
09-23 16:15:15.409 9830-9830/co.example W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
09-23 16:15:15.409 9830-9830/co.example W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
09-23 16:15:15.409 9830-9830/co.example W/System.err: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/co.example-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libconceal.so"
09-23 16:15:15.409 9830-9830/co.example W/System.err:     at com.facebook.crypto.util.SystemNativeCryptoLibrary.loadLibraries(SystemNativeCryptoLibrary.java:50)
09-23 16:15:15.409 9830-9830/co.example W/System.err:     at com.facebook.crypto.util.SystemNativeCryptoLibrary.ensureCryptoLoaded(SystemNativeCryptoLibrary.java:39)
09-23 16:15:15.409 9830-9830/co.example W/System.err:     at com.facebook.crypto.Crypto.isAvailable(Crypto.java:44)
09-23 16:15:15.419 9830-9830/co.example W/System.err:     at co.example.helpers.Helper.encrypt(Helper.java:72)

**Comment by malexmave** [comment]
Same happened to me. The documentation is wrong, you need to put the .so files with their respective folders into the `jniLibs` folder, not the `lib` folder. The folder is located at `src/main/jniLibs`.
